# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-01 03:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store_user', '0001_initial'),
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visits', models.PositiveIntegerField(default=0)),
                ('birthdate', models.DateTimeField()),
                ('phone_number', models.CharField(max_length=10, validators=['validation_phone_number'])),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('signup_ip_address', models.GenericIPAddressField()),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('total_spent', models.PositiveIntegerField(default=0)),
                ('points', models.PositiveIntegerField(default=0)),
                ('deals', models.ManyToManyField(to='content.Deal')),
                ('favorites', models.ManyToManyField(to='content.Item')),
                ('rewards', models.ManyToManyField(to='content.Reward')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='store_user.Store')),
                ('transactions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Transaction')),
                ('used_deals', models.ManyToManyField(related_name='used_deals', to='content.Deal')),
                ('used_rewards', models.ManyToManyField(related_name='used_rewards', to='content.Reward')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
