# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-05 05:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='deals',
            field=models.ManyToManyField(blank=True, to='content.Deal'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='favorites',
            field=models.ManyToManyField(blank=True, to='content.Item'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='rewards',
            field=models.ManyToManyField(blank=True, to='content.Reward'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='transactions',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='content.Transaction'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='used_deals',
            field=models.ManyToManyField(blank=True, related_name='used_deals', to='content.Deal'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='used_rewards',
            field=models.ManyToManyField(blank=True, related_name='used_rewards', to='content.Reward'),
        ),
    ]
