# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-05 05:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_user', '0003_auto_20190105_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='transactions',
        ),
    ]
