# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-30 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_user', '0004_remove_customer_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='birthdate',
            field=models.DateField(),
        ),
    ]
