# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-01 03:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store_user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_rules', models.CharField(max_length=500)),
                ('single_use', models.BooleanField(default=True)),
                ('expires', models.DateTimeField(null=True)),
                ('applications', models.CharField(choices=[('total spent amount', 'total spent amount'), ('spent amount within time', 'spent amount within time'), ('new user', 'new user'), ('reward after purchase', 'reward after purchase'), ('birthday', 'birthday'), ('special day', 'special day'), ('senior customers', 'senior customers'), ('regular reward', 'regular reward'), ('in favorites', 'in favorites')], max_length=50)),
                ('join_date', models.DateTimeField(null=True)),
                ('item_uuid', models.CharField(max_length=50, null=True)),
                ('amount', models.PositiveIntegerField(null=True)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('release_date', models.DateTimeField(null=True)),
                ('earilest_date_of_purchase', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('free', 'free'), ('percent_discount', 'percent_discount'), ('amount_discount', 'amount_discount')], max_length=255)),
                ('percent', models.PositiveIntegerField(null=True)),
                ('amount', models.PositiveIntegerField(null=True)),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=255)),
                ('notification_slogan', models.CharField(max_length=255)),
                ('expired', models.BooleanField(default=False)),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('deal_tag', models.CharField(choices=[('deal', 'deal')], default='deal', editable=False, max_length=20)),
                ('criteria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='content.Criteria')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_user.Store')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField(default=0)),
                ('item_serial_id', models.CharField(max_length=255, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_user.Store')),
            ],
        ),
        migrations.CreateModel(
            name='MetaInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_key', models.CharField(max_length=50)),
                ('item_value', models.CharField(max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('free', 'free'), ('percent_discount', 'percent_discount'), ('amount_discount', 'amount_discount')], max_length=255)),
                ('percent', models.PositiveIntegerField(null=True)),
                ('amount', models.PositiveIntegerField(null=True)),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=255)),
                ('notification_slogan', models.CharField(max_length=255)),
                ('expired', models.BooleanField(default=False)),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('reward_tag', models.CharField(choices=[('reward', 'reward')], default='reward', editable=False, max_length=20)),
                ('criteria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='content.Criteria')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_user.Store')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField(default=0)),
                ('reward_used', models.NullBooleanField(default=None)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_user.Store')),
            ],
        ),
    ]
