# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-31 03:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_rules', models.CharField(max_length=500)),
                ('single_use', models.BooleanField(default=True)),
                ('expires', models.DateTimeField(null=True)),
                ('applications', models.CharField(choices=[('total spent amount', 'total spent amount'), ('spent amount within time', 'spent amount within time'), ('new user', 'new user'), ('reward after purchase', 'reward after purchase'), ('birthday', 'birthday'), ('special day', 'special day'), ('senior customers', 'senior customers'), ('regular reward', 'regular reward'), ('in favorites', 'in favorites')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.PositiveIntegerField(null=True)),
                ('amount', models.PositiveIntegerField(null=True)),
                ('type', models.CharField(choices=[('free', 'free'), ('percent_discount', 'percent_discount'), ('amount_discount', 'amount_discount')], max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=255)),
                ('notification_slogan', models.CharField(max_length=255)),
                ('expired', models.BooleanField(default=False)),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('deal_tag', models.CharField(choices=[('deal', 'deal')], max_length=20)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Criteria')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField(default=0)),
                ('item_serial_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MetaInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Redeemed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('firsted_redeemed', models.DateTimeField()),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.PositiveIntegerField(null=True)),
                ('amount', models.PositiveIntegerField(null=True)),
                ('type', models.CharField(choices=[('free', 'free'), ('percent_discount', 'percent_discount'), ('amount_discount', 'amount_discount')], max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=255)),
                ('notification_slogan', models.CharField(max_length=255)),
                ('expired', models.BooleanField(default=False)),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('reward_tag', models.CharField(choices=[('reward', 'reward')], max_length=20)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Criteria')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField(default=0)),
                ('reward_used', models.NullBooleanField(default=None)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='redeemed',
            name='reward',
            field=models.ManyToManyField(to='content.reward'),
        ),
    ]
