# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-05 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criteria',
            name='earilest_date_of_purchase',
        ),
        migrations.AddField(
            model_name='deal',
            name='deactive_application',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reward',
            name='deactive_application',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='applications',
            field=models.CharField(choices=[('lifetime total spent amount', 'lifetime total spent amount'), ('spent amount within time', 'spent amount within time'), ('new user', 'new user'), ('reward after purchase', 'reward after purchase'), ('birthday', 'birthday'), ('special day', 'special day'), ('senior customers', 'senior customers'), ('regular reward', 'regular reward'), ('in favorites', 'in favorites')], max_length=50),
        ),
    ]
