# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-05 18:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20190104_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='expired',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='expired',
        ),
    ]
