# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-04 01:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_user', '0007_auto_20190403_2121'),
        ('content', '0003_auto_20190105_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number_of_items', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NumOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('maxQuanity', models.PositiveIntegerField(default=10)),
                ('minQuanity', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SelectOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SubOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='abbr',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='active_inventory',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='picture',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='item',
            name='total_sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='items',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='content.Item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='method_of_payment',
            field=models.CharField(choices=[('credit swipe', 'credit swipe'), ('credit dip', 'credit dip')], default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='item_serial_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='selectoption',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Item'),
        ),
        migrations.AddField(
            model_name='selectoption',
            name='selections',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.SubOption'),
        ),
        migrations.AddField(
            model_name='selectoption',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_user.Store'),
        ),
        migrations.AddField(
            model_name='numoption',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Item'),
        ),
        migrations.AddField(
            model_name='numoption',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_user.Store'),
        ),
        migrations.AddField(
            model_name='category',
            name='items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Item'),
        ),
        migrations.AddField(
            model_name='category',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_user.Store'),
        ),
    ]
