# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-01 03:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=2)),
                ('str1', models.CharField(max_length=255)),
                ('str2', models.CharField(max_length=255)),
                ('zipcode', models.PositiveIntegerField()),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=255)),
                ('signup_ip_address', models.GenericIPAddressField()),
                ('business_type', models.CharField(choices=[('Sole', 'Sole'), ('LLC', 'LLC'), ('Corp', 'Corp')], max_length=100)),
                ('api_key', models.CharField(default='e98v62aq7q', editable=False, max_length=10, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Valid_Keys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(editable=False, max_length=10, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('deactive', models.BooleanField(default=False)),
                ('suspended', models.NullBooleanField(default=None)),
                ('cancelled', models.NullBooleanField(default=None)),
            ],
        ),
    ]
