# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-05 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_user', '0005_auto_20190105_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='api_key',
            field=models.CharField(default='x19u73ff6w', editable=False, max_length=10, unique=True),
        ),
    ]
