# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-04 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_user', '0006_auto_20190105_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='api_key',
            field=models.CharField(default='a57s48yn8n', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='valid_keys',
            name='api_key',
            field=models.CharField(editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='valid_keys',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='valid_keys',
            name='suspended',
            field=models.BooleanField(default=False),
        ),
    ]
