# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-11 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_user', '0008_auto_20190403_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='api_key',
            field=models.CharField(default='e55s34nr7c', editable=False, max_length=10),
        ),
    ]
